export const positions = [
    {
        type: 'Defense',
        label: 'Goal Keeper',
        symbol: 'GK',
        color: '#09C609',
        initialPrice: 70,
    },
    {
        type: 'Defense',
        label: 'Left Wing Back',
        symbol: 'LWB',
        color: '#0090DE',
        initialPrice: 40,
    },
    {
        type: 'Defense',
        label: 'Left Back',
        symbol: 'LB',
        color: '#0090DE',
        initialPrice: 40,
    },
    {
        type: 'Defense',
        label: 'Left Center Back',
        symbol: 'LCB',
        color: '#0090DE',
        initialPrice: 30,
    },
    {
        type: 'Defense',
        label: 'Center Back',
        symbol: 'CB',
        color: '#0090DE',
        initialPrice: 30,
    },
    {
        type: 'Defense',
        label: 'Right Center Back',
        symbol: 'RCB',
        color: '#0090DE',
        initialPrice: 30,
    },
    {
        type: 'Defense',
        label: 'Right Back',
        symbol: 'RB',
        color: '#0090DE',
        initialPrice: 40,
    },
    {
        type: 'Defense',
        label: 'Right Wing Back',
        symbol: 'RWB',
        color: '#0090DE',
        initialPrice: 40,
    },
    {
        type: 'Midfield',
        label: 'Center Def. Midfield',
        symbol: 'CDM',
        color: '#EE9F0C',
        initialPrice: 50,
    },
    {
        type: 'Midfield',
        label: 'Left Def. Midfield',
        symbol: 'LDM',
        color: '#EE9F0C',
        initialPrice: 50,
    },
    {
        type: 'Midfield',
        label: 'Right Def. Midfield',
        symbol: 'RDM',
        color: '#EE9F0C',
        initialPrice: 50,
    },
    {
        type: 'Midfield',
        label: 'Left Cen. Midfield',
        symbol: 'LCM',
        color: '#EE9F0C',
        initialPrice: 60,
    },
    {
        type: 'Midfield',
        label: 'Right Cen. Midfield',
        symbol: 'RCM',
        color: '#EE9F0C',
        initialPrice: 60,
    },
    {
        type: 'Midfield',
        label: 'Center Midfield',
        symbol: 'CM',
        color: '#EE9F0C',
        initialPrice: 65,
    },
    {
        type: 'Midfield',
        label: 'Left Midfield',
        symbol: 'LM',
        color: '#EE9F0C',
        initialPrice: 65,
    },
    {
        type: 'Midfield',
        label: 'Right Midfield',
        symbol: 'RM',
        color: '#EE9F0C',
        initialPrice: 65,
    },
    {
        type: 'Midfield',
        label: 'Center Att. Midfield',
        symbol: 'CAM',
        color: '#EE9F0C',
        initialPrice: 70,
    },
    {
        type: 'Midfield',
        label: 'Left Att. Midfield',
        symbol: 'LAM',
        color: '#EE9F0C',
        initialPrice: 65,
    },
    {
        type: 'Midfield',
        label: 'Right Att. Midfield',
        symbol: 'RAM',
        color: '#EE9F0C',
        initialPrice: 65,
    },
    {
        type: 'Midfield',
        label: 'Right Wing Midfield',
        symbol: 'RWM',
        color: '#EE9F0C',
        initialPrice: 60,
    },
    {
        type: 'Midfield',
        label: 'Left Wing Midfield',
        symbol: 'LWM',
        color: '#EE9F0C',
        initialPrice: 60,
    },
    {
        type: 'Forward',
        label: 'Striker',
        symbol: 'ST',
        color: '#EE2E0C',
        initialPrice: 90,
    },
    {
        type: 'Forward',
        label: 'Left Striker',
        symbol: 'LST',
        color: '#EE2E0C',
        initialPrice: 85,
    },
    {
        type: 'Forward',
        label: 'Right Striker',
        symbol: 'RST',
        color: '#EE2E0C',
        initialPrice: 85,
    },
    {
        type: 'Forward',
        label: 'Center Forward',
        symbol: 'CF',
        color: '#EE2E0C',
        initialPrice: 70,
    },
    {
        type: 'Forward',
        label: 'Left Forward',
        symbol: 'LF',
        color: '#EE2E0C',
        initialPrice: 75,
    },
    {
        type: 'Forward',
        label: 'Right Forward',
        symbol: 'RF',
        color: '#EE2E0C',
        initialPrice: 75,
    },
    {
        type: 'Forward',
        label: 'Left Wing',
        symbol: 'LW',
        color: '#EE2E0C',
        initialPrice: 80,
    },
    {
        type: 'Forward',
        label: 'Right Wing',
        symbol: 'RW',
        color: '#EE2E0C',
        initialPrice: 80,
    },
    {
        type: 'Staff',
        label: 'Medical Team',
        symbol: 'MT',
        color: '#8710C3',
        initialPrice: 25,
    },
    {
        type: 'Staff',
        label: 'Tactics Team',
        symbol: 'TT',
        color: '#8710C3',
        initialPrice: 25,
    },
    {
        type: 'Staff',
        label: 'Fitness Team',
        symbol: 'FT',
        color: '#8710C3',
        initialPrice: 30,
    },
    {
        type: 'Staff',
        label: 'Coaching Staff',
        symbol: 'CS',
        color: '#8710C3',
        initialPrice: 30,
    },
    {
        type: 'Staff',
        label: 'Scouting Staff',
        symbol: 'SS',
        color: '#8710C3',
        initialPrice: 35,
    },
    {
        type: 'Staff',
        label: 'Nutritionist',
        symbol: 'NU',
        color: '#8710C3',
        initialPrice: 35,
    },
    {
        type: 'Staff',
        label: 'Physiotherapist',
        symbol: 'PH',
        color: '#8710C3',
        initialPrice: 40,
    },
    {
        type: 'Staff',
        label: 'Goalkeeping Coach',
        symbol: 'GC',
        color: '#8710C3',
        initialPrice: 40,
    },
    {
        type: 'Staff',
        label: 'Strength Coach',
        symbol: 'SC',
        color: '#8710C3',
        initialPrice: 45,
    },
    {
        type: 'Staff',
        label: 'Team Analyst',
        symbol: 'TA',
        color: '#8710C3',
        initialPrice: 45,
    },
    {
        type: 'Staff',
        label: 'Video Analyst',
        symbol: 'VA',
        color: '#8710C3',
        initialPrice: 50,
    },
    {
        type: 'Staff',
        label: 'Equipment Manager',
        symbol: 'EM',
        color: '#8710C3',
        initialPrice: 50,
    },
]

export const Ranks = [
    { rank: 'Youth Coach', maxPoints: 1000 },
    { rank: 'Assistant Coach', maxPoints: 2000 },
    { rank: 'Head Coach', maxPoints: 3000 },
    { rank: 'Reserve Coach', maxPoints: 4000 },
    { rank: 'First Coach', maxPoints: 5000 },
    { rank: 'Tactical Analyst', maxPoints: 6000 },
    { rank: 'Fitness Coach', maxPoints: 7000 },
    { rank: 'Goalkeeper Coach', maxPoints: 8000 },
    { rank: 'Scout', maxPoints: 9000 },
    { rank: 'Football Director', maxPoints: 10000 },
    { rank: 'Academy Director', maxPoints: 11000 },
    { rank: 'Assistant Manager', maxPoints: 12000 },
    { rank: 'Youth Director', maxPoints: 13000 },
    { rank: 'Manager', maxPoints: 14000 },
    { rank: 'Technical Director', maxPoints: 15000 },
];